### ISSUE TITLE
Differences between binary code and gray code

### ISSUE THREAD

**Issue by feiran-l** [elerac/structured_light#5]
Hi! Thank you for the awesome repo. I am a newbie in this field and do have a question as the title goes.

In my understanding, binary code should only contain binary intensities (i.e., white and black), and gray code can contain different intensities. So encoding the same spatial resolution requires fewer grad patterns than binary ones. But in your repo, I see that the number of binary code and gray code are exactly the same, and the gray code is not really gray but binary. Can you give me some hints on this?

**Comment by elerac** [comment]
Hi @SILI1994 !

I can imagine that you are confused. 
In this case, gray is not about color. It is an ordering of the binary numeral system called [Gray code](https://en.wikipedia.org/wiki/Gray_code) (also known as reflected binary code). So, the gray code pattern only contains white and black intensities. And, the number of patterns is the same as the binary code pattern.

In many cases, gray code provides more robust measurements than binary code. I recommend using gray code as the first step.

Here are some helpful slides.
- [Build Your Own 3D Scanner: 3D Scanning with Structured Lighting](https://www.slideshare.net/dlanman/build-your-own-3d-scanner-3d-scanning-with-structured-lighting)
  - pages 4 and 5 describe binary and gray code.
- [Structured Light II](http://www.sci.utah.edu/~gerig/CS6320-S2013/Materials/CS6320-CV-S2012-StructuredLight-II.pdf)
  - This slide introduces a wide range of techniques of structured light.

**Comment by elerac** [comment]
I noticed that you are a student of Matsushita's lab. So I recommend you to read the following book.
- [Active Lighting and Its Application for Computer Vision: 40 Years of History of Active Lighting Techniques](https://link.springer.com/book/10.1007/978-3-030-56577-0)

This book is paid for, but you can probably get it because Prof. Yasuyuki Matsushita co-authored it.
Both binary and gray codes are described in detail in subsection 2.5.1 (2: Geometry -> 2.5: PointCorrespondenceProblem ->  2.5.1:Temporal Encoding).

**Comment by feiran-l** [comment]
Hi! Thank you for the awesome answer and the links! I think I have misunderstood the terminology gray code. I was referring to Sec. 2.2 of [this](https://www.osapublishing.org/aop/fulltext.cfm?uri=aop-3-2-128&id=211561) and their *gray pattern* therein. Now I know their differences :).
